name: Waka Readme

on:
  schedule:
    # Runs at 12:00 PM
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SYMBOL_VERSION: 2
          SHOW_LANGUAGE_PER_REPO: "False"
          COMMIT_BY_ME: "True"
          COMMIT_USERNAME: "ein-wakatime"
          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "False"

          # commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
